# Generated by Django 3.2.18 on 2023-04-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('token', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
    ]
